use std::sync::Arc;

use collections::HashMap;
use ui::IconName;

const ICON_GLYPHS: &[(IconName, char)] = &[
    (IconName::ChevronRight, '▸'),
    (IconName::TriangleRight, '▸'),
    (IconName::PlayFilled, '▸'),
    (IconName::PlayOutlined, '▸'),
    (IconName::ChevronDown, '▾'),
    (IconName::Triangle, '▾'),
    (IconName::ChevronUp, '▴'),
    (IconName::ChevronLeft, '◂'),
    (IconName::ChevronUpDown, '↕'),
    (IconName::ChevronDownUp, '↕'),
    (IconName::ExpandVertical, '↕'),
    (IconName::FoldVertical, '↕'),
    (IconName::ExpandUp, '↥'),
    (IconName::ExpandDown, '↧'),
    (IconName::Folder, '▸'),
    (IconName::FolderOpen, '▾'),
    (IconName::Close, '×'),
    (IconName::GenericClose, '×'),
    (IconName::XCircle, '×'),
    (IconName::XCircleFilled, '×'),
    (IconName::Check, '✓'),
    (IconName::CheckDouble, '✓'),
    (IconName::TodoComplete, '✓'),
    (IconName::TodoProgress, '◐'),
    (IconName::TodoPending, '○'),
    (IconName::Dash, '−'),
    (IconName::GenericMinimize, '−'),
    (IconName::SquareMinus, '−'),
    (IconName::Plus, '+'),
    (IconName::SquarePlus, '+'),
    (IconName::FolderAdd, '+'),
    (IconName::FolderInclude, '+'),
    (IconName::Ellipsis, '…'),
    (IconName::ArrowLeft, '←'),
    (IconName::ArrowRight, '→'),
    (IconName::ForwardArrow, '→'),
    (IconName::ArrowRightLeft, '⇄'),
    (IconName::ArrowUp, '↑'),
    (IconName::ArrowUpRight, '↑'),
    (IconName::ArrowDown, '↓'),
    (IconName::ArrowDownRight, '↓'),
    (IconName::ForwardArrowUp, '↳'),
    (IconName::ReplyArrowRight, '↱'),
    (IconName::Circle, '●'),
    (IconName::Indicator, '●'),
    (IconName::SquareDot, '●'),
    (IconName::LoadCircle, '◌'),
    (IconName::MagnifyingGlass, '⌕'),
    (IconName::ToolSearch, '⌕'),
    (IconName::FolderSearch, '⌕'),
    (IconName::Warning, '⚠'),
    (IconName::ToolDiagnostics, '⚠'),
    (IconName::Info, 'ℹ'),
    (IconName::CircleHelp, 'ℹ'),
    (IconName::Settings, '⚙'),
    (IconName::FileToml, '⚙'),
    (IconName::Menu, '≡'),
    (IconName::Split, '◨'),
    (IconName::SplitAlt, '◨'),
    (IconName::ThreadsSidebarLeftClosed, '◧'),
    (IconName::ThreadsSidebarLeftOpen, '◧'),
    (IconName::ThreadsSidebarRightClosed, '◨'),
    (IconName::ThreadsSidebarRightOpen, '◨'),
    (IconName::Maximize, '□'),
    (IconName::GenericMaximize, '□'),
    (IconName::MaximizeAlt, '□'),
    (IconName::GenericRestore, '❐'),
    (IconName::Minimize, '_'),
    (IconName::Bell, '♪'),
    (IconName::BellDot, '♪'),
    (IconName::BellOff, '♪'),
    (IconName::BellRing, '♪'),
    (IconName::ToolNotification, '♪'),
    (IconName::GitBranch, '⎇'),
    (IconName::GitBranchPlus, '⎇'),
    (IconName::GitGraph, '⎇'),
    (IconName::GitWorktree, 'Ψ'),
    (IconName::PullRequest, '↰'),
    (IconName::GitMergeConflict, '≠'),
    (IconName::Terminal, '$'),
    (IconName::TerminalAlt, '$'),
    (IconName::ToolTerminal, '$'),
    (IconName::ReplNeutral, '❯'),
    (IconName::FileTree, '≣'),
    (IconName::ListTree, '≣'),
    (IconName::Diff, '±'),
    (IconName::FileDiff, '±'),
    (IconName::Slash, '/'),
    (IconName::Hash, '#'),
    (IconName::AtSign, '@'),
    (IconName::Envelope, '@'),
    (IconName::Lock, '⚿'),
    (IconName::LockOff, '⚿'),
    (IconName::Star, '★'),
    (IconName::StarFilled, '★'),
    (IconName::Trash, '⌫'),
    (IconName::ToolDeleteFile, '⌫'),
    (IconName::Copy, '⧉'),
    (IconName::ToolCopy, '⧉'),
    (IconName::FileMultiple, '⧉'),
    (IconName::CaseSensitive, 'C'),
    (IconName::WholeWord, 'W'),
    (IconName::Regex, '*'),
    (IconName::Replace, '⇄'),
    (IconName::ReplaceAll, '⇉'),
    (IconName::ReplaceNext, '↷'),
    (IconName::SelectAll, '⊞'),
    (IconName::ArrowCircle, '↻'),
    (IconName::RotateCw, '↻'),
    (IconName::RefreshTitle, '↻'),
    (IconName::Rerun, '↻'),
    (IconName::RotateCcw, '↺'),
    (IconName::Undo, '↺'),
    (IconName::FileIgnored, '∅'),
    (IconName::FileLock, '⚿'),
    (IconName::Quote, '"'),
    (IconName::Pin, '⊙'),
    (IconName::Unpin, '⊙'),
    (IconName::Stop, '■'),
    (IconName::Power, '■'),
    (IconName::CursorIBeam, 'I'),
    (IconName::Eye, '◉'),
    (IconName::EyeOff, '⊘'),
    (IconName::File, '▯'),
    (IconName::FileDoc, '¶'),
    (IconName::FileGeneric, '¶'),
    (IconName::FileTextFilled, '¶'),
    (IconName::FileTextOutlined, '¶'),
    (IconName::FileMarkdown, '¶'),
    (IconName::Reader, '¶'),
    (IconName::Notepad, '¶'),
    (IconName::Book, '¶'),
    (IconName::DiffSplit, '◫'),
    (IconName::DiffSplitAuto, '◫'),
    (IconName::DiffUnified, '▤'),
    (IconName::Filter, 'ƒ'),
    (IconName::FilterFunnel, 'ƒ'),
    (IconName::DebugBreakpoint, '●'),
    (IconName::DebugDisabledBreakpoint, '○'),
    (IconName::DebugLogBreakpoint, '◆'),
    (IconName::DebugDisabledLogBreakpoint, '◇'),
    (IconName::DebugIgnoreBreakpoints, '○'),
    (IconName::Debug, '¤'),
    (IconName::DebugContinue, '▸'),
    (IconName::DebugContinueThread, '▸'),
    (IconName::DebugPause, '‖'),
    (IconName::DebugStepOver, '↷'),
    (IconName::DebugStepInto, '↓'),
    (IconName::DebugStepOut, '↑'),
    (IconName::DebugDetach, '×'),
    (IconName::ArrowDown10, '#'),
    (IconName::Flame, '!'),
    (IconName::BoltFilled, '↯'),
    (IconName::BoltOutlined, '↯'),
    (IconName::HistoryRerun, '↻'),
    (IconName::GitCommit, '•'),
    (IconName::FileGit, '•'),
    (IconName::Download, '↓'),
    (IconName::CloudDownload, '↓'),
    (IconName::ListCollapse, '↕'),
    (IconName::ListTodo, '☐'),
    (IconName::Keyboard, '⌨'),
    (IconName::Command, '⌘'),
    (IconName::Control, '⌃'),
    (IconName::Option, '⌥'),
    (IconName::Shift, '⇧'),
    (IconName::Return, '⏎'),
    (IconName::Escape, '⎋'),
    (IconName::Backspace, '⌫'),
    (IconName::Tab, '⇥'),
    (IconName::PageUp, '⇞'),
    (IconName::PageDown, '⇟'),
    (IconName::Space, '␣'),
    (IconName::TextWrap, '↵'),
    (IconName::TextUnwrap, '⇸'),
    (IconName::Bookmark, '⚑'),
    (IconName::Code, '‹'),
    (IconName::FileCode, '‹'),
    (IconName::FileCodeOff, '⊘'),
    (IconName::Blocks, '⊞'),
    (IconName::Table, '▦'),
    (IconName::Image, '▣'),
    (IconName::Link, '∞'),
    (IconName::Pencil, '✎'),
    (IconName::ToolPencil, '✎'),
    (IconName::LocationEdit, '✎'),
    (IconName::PencilUnavailable, '⊘'),
    (IconName::Scissors, '✄'),
    (IconName::ListX, '⌧'),
    (IconName::Eraser, '⌧'),
    (IconName::Clock, '◷'),
    (IconName::CountdownTimer, '◷'),
    (IconName::Sparkle, '✦'),
    (IconName::ZedAssistant, '✦'),
    (IconName::ZedAgentTwo, '✦'),
    (IconName::AiEdit, '✦'),
    (IconName::ZedAgent, 'ℤ'),
    (IconName::AiZed, 'ℤ'),
    (IconName::AiClaude, '✻'),
    (IconName::AcpRegistry, 'A'),
    (IconName::ZedSrcCustom, 'C'),
    (IconName::ZedSrcExtension, 'E'),
    (IconName::Thread, '❝'),
    (IconName::ThreadFromSummary, '❝'),
    (IconName::Chat, '❝'),
    (IconName::Send, '➤'),
    (IconName::QueueMessage, '➢'),
    (IconName::Compact, '⇲'),
    (IconName::FastForward, '≫'),
    (IconName::FastForwardOff, '≫'),
    (IconName::ThinkingMode, '∴'),
    (IconName::ThinkingModeOff, '∴'),
    (IconName::ToolThink, '∴'),
    (IconName::ToolHammer, '⚒'),
    (IconName::ToolWeb, '◍'),
    (IconName::Public, '◍'),
    (IconName::Crosshair, '⊕'),
    (IconName::ThumbsUp, '▲'),
    (IconName::ThumbsDown, '▼'),
    (IconName::Archive, '⊟'),
    (IconName::ZedPredict, '»'),
    (IconName::ZedPredictUp, '↑'),
    (IconName::ZedPredictDown, '↓'),
    (IconName::ZedPredictDisabled, '⊘'),
    (IconName::ZedPredictError, '×'),
    (IconName::Person, '♙'),
    (IconName::UserCheck, '♙'),
    (IconName::UserGroup, '♙'),
    (IconName::UserRoundPen, '♙'),
    (IconName::UserArrowUp, '♙'),
    (IconName::Screen, '▭'),
    (IconName::ThisWindow, '▭'),
    (IconName::Server, 'Ξ'),
    (IconName::Box, '❒'),
    (IconName::BoxOpen, '❒'),
    (IconName::Exit, '↦'),
    (IconName::Disconnected, '⊘'),
    (IconName::OnCall, '☏'),
    (IconName::FolderShare, '⇪'),
    (IconName::FolderShared, '⇪'),
    (IconName::Share, '⇪'),
    (IconName::SignalLow, '▂'),
    (IconName::SignalMedium, '▄'),
    (IconName::SignalHigh, '▆'),
];

pub fn icon_glyphs() -> impl Fn(&str) -> Option<char> + 'static {
    let glyphs: HashMap<Arc<str>, char> = ICON_GLYPHS
        .iter()
        .map(|(icon, glyph)| (icon.path(), *glyph))
        .collect();
    move |path| {
        if path.contains("file_icons/") {
            let name = path.rsplit('/').next()?.strip_suffix(".svg")?;
            return Some(match name {
                "folder" | "chevron_right" => '▸',
                "folder_open" | "chevron_down" => '▾',
                "chevron_up" => '▴',
                "chevron_left" => '◂',
                _ => '·',
            });
        }
        glyphs.get(path).copied()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn icons_map_to_single_width_glyphs() {
        let glyph = icon_glyphs();
        assert_eq!(glyph(&IconName::ChevronRight.path()), Some('▸'));
        assert_eq!(glyph("icons/file_icons/rust.svg"), Some('·'));
        assert_eq!(glyph("icons/file_icons/folder_open.svg"), Some('▾'));
        assert_eq!(glyph(&IconName::AiOpenAi.path()), None);
        let wide: Vec<_> = ICON_GLYPHS
            .iter()
            .filter(|(_, ch)| unicode_width::UnicodeWidthChar::width(*ch) != Some(1))
            .collect();
        assert!(wide.is_empty(), "icons with wide glyphs: {wide:?}");
    }
}
